### PR TITLE
Update community.yml

### PR DESCRIPTION
**Pull request by ques123**

### CODE REVIEW

**Comment by skatkov** [comment]
Thanks for contribution :-)
I was looking for any free communities to add, i'll ask around people if they consider it valuable (i see some familiar names). 

Sorry, i try to keep list short and to the point ;)

**Comment by ques123** [comment]
Sure thing. Thanks.

Chris Porter
CEO of questio.co.uk

**Comment by skatkov** [comment]
I've heard some feedback from people and they seem to like your community, besides that it's not that active :)
Just for the sake of alternative, i would like to add it. Can you please rebase your pull request so i can merge it?

**Comment by ques123** [comment]
Hey, sorry, Im a github noob and don't know what you're asking :)

Chris Porter
Director @ questio.co.uk
[about http://questio.co.uk/team / contact info http://porter.im/]

**Comment by skatkov** [comment]
Sorry, it took some time. But i've added your link to website myself (without rebuilding your pull request) :)

So, closing this pull request. Thanks for contribution.

**Pull request closed without merging**
